### ISSUE TITLE
已经Pip安装了，环境也没有问题，但是还是报错没有histcite模块

### ISSUE THREAD

**Issue by hehx001** [doublessay/histcite-python#1]
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 /Users/Hehx/PycharmProjects/phd/histcite.py 
Traceback (most recent call last):
  File "/Users/Hehx/PycharmProjects/phd/histcite.py", line 10, in <module>
    from histcite.process_file import ProcessFile
  File "/Users/Hehx/PycharmProjects/phd/histcite.py", line 10, in <module>
    from histcite.process_file import ProcessFile
ModuleNotFoundError: No module named 'histcite.process_file'; 'histcite' is not a package

**Comment by doublessay** [comment]
你程序文件名为histcite.py，与模块名称重了，修改下就行
