### ISSUE TITLE
ValueError: You are trying to merge on object and int64[pyarrow] columns for key 'BP'. 

### ISSUE THREAD

**Issue by Mrlouis6** [doublessay/histcite-python#6]
### 问题描述

在一个月前，使用成功过。最近却用不起来了，windows11 64位电脑，在anaconda 新建的虚拟环境中安装python-histcite并激活后（其中python版本3.12）输入命令：histcite e:/sci wos --top 10 --disable_timeline，一直报错。但是显示成功读取数据的，我也检查了有没有下载错数据格式（Tab delimited file/制表符分隔文件，导出内容选择 Full Record and Cited References/全记录与引用的参考文献），没有下载错，但是就是报错，所以我留言反馈一下。不知道是不是我命令输入错了，但是一个月前我也是按照说明书来的，但现在就不行，

### 报错信息

(histcite) E:\sci>histcite e:/sci wos --top 10 --disable_timeline
共读取 50 条数据，去重后剩余 50 条
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Scripts\histcite.exe\__main__.py", line 7, in <module>
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\__main__.py", line 48, in cli
    citation_relation = process.process_citation(refs_df)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\process_file.py", line 94, in process_citation
    cited_doc_id_series = RecognizeReference.recognize_wos_reference(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\recognize_reference.py", line 86, in recognize_wos_reference
    result = RecognizeReference.recognize_refs_factory(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\recognize_reference.py", line 39, in recognize_refs_factory
    shared_df = pd.merge(
                ^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 804, in __init__
    self._maybe_coerce_merge_keys()
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 1479, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and int64[pyarrow] columns for key 'BP'. If you wish to proceed you should use pd.concat

### 版本信息

python: 3.12.0.final.0
OS: Windows 11
pandas: 2.1.4
pyarrow: 14.0.1

### conda list

packages in environment at E:\SoftWare_In_E\anaconda3\envs\histcite:

Name                    Version                   Build  Channel
bzip2                     1.0.8                he774522_0
ca-certificates           2023.08.22           haa95532_0
et-xmlfile                1.1.0                    pypi_0    pypi
expat                     2.5.0                hd77b12b_0
histcite-python           1.0.1                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
numpy                     1.26.2                   pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.0.12               h2bbff1b_0
pandas                    2.1.4                    pypi_0    pypi
pip                       23.3.1          py312haa95532_0
pyarrow                   14.0.1                   pypi_0    pypi
python                    3.12.0               h1d929f7_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
setuptools                68.2.2          py312haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tzdata                    2023.3                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2          py312haa95532_0
xz                        5.4.5                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0

### 使用数据源

Web of Science

**Comment by doublessay** [comment]
谢谢反馈！命令没什么问题。
根据报错信息应该就是合并时 `BP` 字段（开始页）既有 `int` 又有 `object` 类型。
不知道你当前测试的数据集是否是一个月前使用成功时的数据集，如果方便的话，请上传一份本次使用的数据集或能复现bug的最小数据集，帮助进一步排查问题。

**Comment by Mrlouis6** [comment]
感谢作者大佬回复！

以上三个文件的报错提示为（这三个文件是我用一个软件下载的）:
[1.txt](https://github.com/doublessay/histcite-python/files/13693020/1.txt)
[2.txt](https://github.com/doublessay/histcite-python/files/13693021/2.txt)
[3.txt](https://github.com/doublessay/histcite-python/files/13693023/3.txt)

(histcite) C:\Users>histcite e:/sci wos --top 10 --disable_timeline
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Scripts\histcite.exe\__main__.py", line 7, in <module>
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\__main__.py", line 45, in cli
    docs_df = ReadFile(folder_path, args.source).read_all()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\read_file.py", line 260, in read_all
    docs_df = self._concat_df(ReadWosFile.read_wos_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\read_file.py", line 227, in _concat_df
    raise FileNotFoundError("No valid file in the folder")
FileNotFoundError: No valid file in the folder

以下一个文件的报错提示为（这个文件是我标标准准的手工去下的）：
[savedrecs.txt](https://github.com/doublessay/histcite-python/files/13693039/savedrecs.txt)

(histcite) C:\Users>histcite e:/sci wos --top 10 --disable_timeline
共读取 50 条数据，去重后剩余 50 条
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Scripts\histcite.exe\__main__.py", line 7, in <module>
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\__main__.py", line 48, in cli
    citation_relation = process.process_citation(refs_df)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\process_file.py", line 94, in process_citation
    cited_doc_id_series = RecognizeReference.recognize_wos_reference(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\recognize_reference.py", line 86, in recognize_wos_reference
    result = RecognizeReference.recognize_refs_factory(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\histcite\recognize_reference.py", line 39, in recognize_refs_factory
    shared_df = pd.merge(
                ^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 804, in __init__
    self._maybe_coerce_merge_keys()
  File "E:\SoftWare_In_E\anaconda3\envs\histcite\Lib\site-packages\pandas\core\reshape\merge.py", line 1479, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and int64[pyarrow] columns for key 'BP'. If you wish to proceed you should use pd.concat


以上我最近在web of science下载的数据集。我也是首次使用github的上传文件功能，如果上传失败的话，麻烦大佬再跟我说一下，我看到一定及时配合上传，如果是我个人操作不当出现的问题，我就提前给大佬道歉一下浪费时间了。

**Comment by doublessay** [comment]
1. `1.txt` 等三个文件提示没有有效的文件，是因为 `histcite-python` 会根据文件名筛选有效的数据文件，就是从数据库中导出文件的原始名称。这一点在 `README.md` 有所说明，但可能不太明确。后续这一块可能会做出调整，不再做文件名的限制。

- Web of Science: savedrecs.txt, savedrecs (1).txt, ...
- CSSCI: LY_.txt, ...
- Scopus: scopus.csv, scopus (1).txt, ...

2. 问题已修复。请更新到 [1.02版本](https://pypi.org/project/histcite-python/1.0.2/) 使用。

**Comment by Mrlouis6** [comment]
(histcite) C:\Users>histcite e:/sci wos --top 10 --disable_timeline
共读取 500 条数据，去重后剩余 500 条
(histcite) C:\Users>

这次按照说明书“从数据库中导出文件的原始名称”后使用成功，感谢大佬伟大的开源精神，好评，小弟膜拜了。
